### PR TITLE
make static image format configurable, add support for animated avatars

### LINKED ISSUE #9: Photos of discord-users not showing in HA-app
I don't know if this is caused by this integration or by HA itself, so please feel free to close this if you think it's HA's fault ;)

When displaying the discord-user-entities in lovelace, I can see the users profilepictures just fine. When i'm loading the same dashboard in the HA-app, the pictures are gone.

Browser:
image

App:
image

### PR DESCRIPTION
**Pull request by niklaswa**
closes #9

### CODE REVIEW

**Comment by LordBoos** [comment]
Hello and thank you.
Have you considered that PNG images are much bigger than WEBP? Eg. my own discord avatar has 150 KB in WEBP format and 1.8 MB in PNG format. That might be a little problematic for mobile data plans.
I think that a configuration option to change formats would be better approach.

**Comment by niklaswa** [comment]
That's true. Maybe that would be better.
In general, the avatar url should use [this](https://discordpy.readthedocs.io/en/latest/api.html#discord.Webhook.avatar_url_as) function, so GIF avatars are supported too. But I would have to deal more with the architecture of Python applications to understand exactly where to do what.

**Comment by niklaswa** [comment]
I implemented it. 😄

**Comment by LordBoos** [comment]
Good job. Have you tested it? I had some problems with serialization while passing url to watcher directly like you do. Or does `avatar_url_as` method escapes the URL somehow?

**Comment by niklaswa** [comment]
I tested it with users with default avatars, normal avatars and animated avatars in Chrome and Safari and had no problems.

**Comment by LordBoos** [comment]
Yea I just tested it myself and got no issues. Thank you for your contribution. 🙂

**Pull request merged**
